server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /netdata/ {
        proxy_pass http://192.168.1.101:19999/;
        proxy_set_header Host localhost;
    }

    location /action/ {
        proxy_pass http://192.168.1.101:8897/;
        proxy_set_header Host localhost;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
